# Generated by Django 5.2.6 on 2025-09-13 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(limit_choices_to={'role': 'creator'}, to=settings.AUTH_USER_MODEL, verbose_name='suit'),
        ),
    ]
